### PR TITLE
Update zh_TW.php

### PR DESCRIPTION
**Pull request by oopsFrogs**
This is the correct traditional Chinese version that used in Taiwan.

### CODE REVIEW

**Comment by petercoles** [comment]
Thank you for these corrections. Unfortunately the information you've corrected isn't managed by this project, which is just a wrapper to deliver it.

Instead this project is automatically updated from data maintained by the [International Components for Unicode (ICU) project](http://site.icu-project.org/home), so I recommend submitting these corrections to them and then the changes will be be automatically made here once they've worked their way through ICU's processes.

**Comment by oopsFrogs** [comment]
Thank you for your great works! 
But I check the ICU, the names of the countries under zh_TW locale are correct, I post the link below.
[http://demo.icu-project.org/icu-bin/locexp?_=zh_Hant&SHOWCountries=1#Countries](url)

**Comment by petercoles** [comment]
Thank you for that link. However, it points to the ICU names for the zh_Hant locale rather than the zh_TW locale for which you submitted the pull request. There's also a zh_Hant_TW locale that also has already the values in your pull request. You could use either of these to get the results you want.

The zh_TW locale is interesting. The ICU site does indeed now have the names tin your pull request, but it also has a big warning notice that they are not verified, which may be why they haven't yet made it into the data used by this package. Once the verification has been completed by the ICU project and the changes form part of the data automatically imported here, then they'll be available to use under zh_TW.

**Comment by oopsFrogs** [comment]
I see, thank you!

**Pull request closed without merging**
